on:
  release

name: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Load cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}


      - name: Install alsa
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev
        if: ${{ runner.os == 'Linux' }}

      - name: Install udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev
        if: ${{ runner.os == 'Linux' }}

      - name: Build
        run: cargo build --release

      - name: Store Binary
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'target/release/{tomi,tomi.exe}'
