on:
  release:
    types: [published]

name: Release

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Load cache
        # See https://github.com/actions/cache/issues/403
        if: runner.os != 'macOS'
        uses: actions/cache@v3.0.7
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Store Binary Windows
        if: ${{ runner.os == 'Windows' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/release/tomi.exe
          asset_name: tomi.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Store Binary Osx
        if: ${{ runner.os == 'macOS' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/release/tomi
          asset_name: tomi-osx
          asset_content_type: application/octet-stream
