on:
  push:
    branches:
      - master
  pull_request:

name: Test

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    needs: [clippy, fmt]
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Load cache
        # See https://github.com/actions/cache/issues/403
        if: runner.os != 'macOS'
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install alsa
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev
        if: ${{ runner.os == 'Linux' }}

      - name: Install udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev
        if: ${{ runner.os == 'Linux' }}

      - name: Run tests
        run: cargo test --workspace

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: Install alsa
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev

      - name: Install udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev

      - name: Load cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run clippy
        run: cargo clippy
